if(isset($_REQUEST['question1']))
	{
		if($_REQUEST['question1']==$op1){
			$answer2 = $_REQUEST['question1'];
		if($answer2==$answer){
		
		ECHO 'CORRECT';
		}
		
		else{
			ECHO 'WRONG';
			$cor='WRONG';
		}
	}
	if($_REQUEST['question1']==$op2){
			$answer2 = $_REQUEST['question1'];
		if($answer2==$answer){
		
		ECHO 'CORRECT';
		}
		
		else{
			ECHO 'WRONG';
			#$cor='WRONG';
		}
	}
	if($_REQUEST['question1']==$op3){
			$answer2 = $_REQUEST['question1'];
		if($answer2==$answer){
		
		ECHO 'CORRECT';
		}
		
		else{
			ECHO 'WRONG';
			#$cor='WRONG';
		}
	}
	if($_REQUEST['question1']==$op4){
			$answer2 = $_REQUEST['question1'];
		if($answer2==$answer){
		
		ECHO 'CORRECT';
		}
		
		else{
			ECHO 'WRONG';
			#$cor='WRONG';
		}
	}
	}
	
	
	#$name='marios';
# $query="INSERT INTO examresult(name,Qid,answer,result) VALUES('$name','$qno','$answer','$cor')";
 